name: mapbox_navigation_sdk
description: A Flutter package for Mapbox Navigation SDK with native Android and iOS implementation. Provides turn-by-turn navigation with route preview and progress tracking.
version: 1.0.0
homepage: https://github.com/yourusername/mapbox_navigation_sdk
repository: https://github.com/yourusername/mapbox_navigation_sdk
issue_tracker: https://github.com/yourusername/mapbox_navigation_sdk/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: mapbox.navigation.sdk.mapbox_navigation_sdk
        pluginClass: MapboxNavigationSdkPlugin
      ios:
        pluginClass: MapboxNavigationSdkPlugin
